### ISSUE TITLE
Scrolling Problem After Updating to 2.8.0

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#2044]
Hi,

Thank you for this great script.

When it runs at the first time, scrolling is OK, but scrolling down and up to the first section again, it gives an error (jquery.fullPage.js:2767 Uncaught TypeError: scroller.wheelOff is not a function)

Isolated link
http://codepen.io/anon/pen/BzaEpb/

Is it me or do you have the same error ?

Thank you,

**Comment by alvarotrigo** [comment]
I spotted it also in a jsfiddle demo. Not quite sure why it is not firing in all cases but I'll solve it tomorrow.

**Comment by Vemon** [comment]
I got the same issue, I fixed it by changing from this:
`"main": [
    "dist/jquery.fullPage.js",
    "dist/jquery.fullPage.css",
    "dist/jquery.fullPage.scss",
    "vendors/jquery.easings.min.js",
    "vendors/scrolloverflow.min.js"
  ],`
to this:
`"main": [
    "vendors/jquery.easings.min.js",
    "vendors/scrolloverflow.min.js",
    "dist/jquery.fullPage.js",
    "dist/jquery.fullPage.css",
    "dist/jquery.fullPage.scss"
  ],`

**Comment by alvarotrigo** [comment]
@Vemon that has nothing to do with the problem.

**Comment by Vemon** [comment]
In my case the `IScroll` was undefined so the `wheelOn` and `wheelOff`function weren't added to the `IScroll.prototype`, thus causing the exception. I guessed the `scrolloverflow.min.js` wasn't included before Fullpage so I went and override the order in my bower.json file, then it all worked out.

**Comment by alvarotrigo** [comment]
@Vemon the problem can be reproduced without even using `scrollOverflow:true`. Where IScroll is not even necessary. In fact, even when including it you'll still getting the error as you can see [here](http://jsfiddle.net/97tbk/1286/).

Anyways, I've solved it on the `dev` branch and would probably release a new version of fullpage.js soon.

**Comment by Vemon** [comment]
Thanks, and awesome library btw.

**Comment by Alex360hd** [comment]
I confirm the issue, even with the dev version. Obliged to rollback to 2.7.9 to make it works again..

**Comment by alvarotrigo** [comment]
2.8.1 just released solving it.

**Comment by sjaakbanaan** [comment]
Hi Álvaro, i'm still having the issue with 2.8.1.

My settings are:
`	$('#fullpage').fullpage({
		anchors: fullpage_anchors,
		menu: '#menu',
		scrollingSpeed: 1000,
        normalScrollElementTouchThreshold: 10,
		scrollOverflow: true,
        normalScrollElements: '#popup-listings, nav, #popup-register',
		verticallyCentered: false,
	});`

**Comment by alvarotrigo** [comment]
@sjaakbanaan  Please add a link in jsfiddle or codepen with the reproduction. (no external js or css )

**Comment by sjaakbanaan** [comment]
It still exists in: http://codepen.io/anon/pen/BzaEpb/ (scroll all the way down with mousewheel, and then scroll up. I'm getting stuck on de section with the text 'One' (second section) and DOM returns: 
` Uncaught TypeError: scroller.wheelOff is not a function`

**Comment by alvarotrigo** [comment]
@sjaakbanaan you got the wrong order importing the external JS files. Just use `scrolloverflow.js` before fullpage.js.

**Comment by sjaakbanaan** [comment]
that fixed it, thanks (for this awesome script)!

**Comment by meceware** [comment]
Thank you for the fix. Order of the JS works great.
