### ISSUE TITLE
Not support webpack?

### ISSUE THREAD

**Issue by rayliao** [alvarotrigo/fullPage.js#2129]
After installed `fullpage.js` by npm, and I used it throught webpack like this:

```
import 'fullpage.js';

$(function() {
    $('#fullpage').fullpage({
        navigation: true
    });
});
```

then output error like this:
```
jQuery.Deferred exception: $(...).fullpage is not a function 
TypeError: $(...).fullpage is not a function
```

**Comment by alvarotrigo** [comment]
You might need to use `jquery.fullpage.js`. Not just `fullpage.js`.

fullPage.js provides support for the universal module definition (UMD), which includes AMD, commonJS and node modules.

**Comment by rravikot** [comment]
For anyone who might still be confused, it works if you import it like this:

`import 'fullpage.js/jquery.fullpage.js';`

**Comment by ShavidzeT** [comment]
@rravikot I've imported just like you but the problem is same :)

**Comment by alvarotrigo** [comment]
@ShavidzeT are you using the latest fullpage.js version? 2.8.5 ?

**Comment by ShavidzeT** [comment]
@alvarotrigo Problem has been solved.
I have created vendor.entry.js source file with following content
``` javascript
window.$ = window.jQuery = require('jquery')
import 'fullpage.js/jquery.fullPage.js'
```
and bundle of this file is imported in html above application logic bundle

**Comment by edwardfhsiao** [comment]
i had the error TypeError: $(...).fullpage is not a function when working my project with fullpage.js@2.8.7.
Then I tried to downgrade it to fullpage.js@2.8.6, and it wont work first. However I found there is a node_modules directry contains another jquery inside the fullpage.js. After removing it, fullpage.js worked.

├── node_modules
│   ├── fullpage.js
│   │   ├── README.md
│   │   ├── jquery.fullPage.js
│   │   ├── package.json
│   │   ├── jquery.fullPage.css
│   │   ├──vendors
│   │   └── **node_modules**
│   │   │   ├── **jquery**

If anyone had the same problem with fullpage.js@2.8.7, maybe could try to downgrade it to fullpage.js@2.8.6 and `rm -rf my_awesome_project/node_modules/fullpage.js/node_modules`

**Comment by alvarotrigo** [comment]
@edwardfhsiao I don't see why it shouldn't work with 2.8.7. There was [a small change in the package.json file](https://github.com/alvarotrigo/fullPage.js/commit/203f0b706bbe065111d8435b1049f4483756921f) but [the rest of changes](https://github.com/alvarotrigo/fullPage.js/releases) shouldn't interfiere at all as far as I know.

**Comment by edwardfhsiao** [comment]
@alvarotrigo Yes, You were right. I tried 2.8.7 again and it worked. 
The fundamental interfierence is the Jquery inside the fullpage.js/node_modules. 
Thanks for your time.

**Comment by alvarotrigo** [comment]
@edwardfhsiao as far as I know fullPage.js doesn't include any node_modules by default. They are only necessary if you want to create your own build as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#build-tasks). Also, even when doing so, there's no jquery dev dependency in the [package.json file](https://github.com/alvarotrigo/fullPage.js/blob/master/package.json).

**Comment by edwardfhsiao** [comment]
@alvarotrigo yeah, I guess it must be some setting issue irrelevant to fullpage.js. I also encountered the same problem with pickadate and ujs in the past. 
Fullpage.js is pretty cool by the way, really appreciate

**Comment by Rogant** [comment]
I add to my code
`import 'fullpage.js/jquery.fullPage.js';`

And then i get
`Module not found: Error: Can't resolve 'fullpage.js/jquery.fullPage.js'`
